# Generated by Django 4.2.25 on 2025-11-06 20:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0003_report_other_issue'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('description', models.TextField()),
                ('short_description', models.CharField(blank=True, help_text='Brief summary for cards/listings', max_length=300)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('approved', 'Approved'), ('in_progress', 'In Progress'), ('on_hold', 'On Hold'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='planned', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('location', models.CharField(help_text='Area/ward where project is located', max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('ward', models.CharField(blank=True, help_text='Ward number or name', max_length=100)),
                ('estimated_budget', models.DecimalField(blank=True, decimal_places=2, help_text='Budget in INR', max_digits=15, null=True)),
                ('actual_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Actual cost if completed', max_digits=15, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('expected_completion_date', models.DateField(blank=True, null=True)),
                ('actual_completion_date', models.DateField(blank=True, null=True)),
                ('project_manager', models.CharField(blank=True, help_text='Name of project manager or authority', max_length=200)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='projects/%Y/%m/')),
                ('benefits', models.TextField(blank=True, help_text='Benefits to citizens/community')),
                ('challenges', models.TextField(blank=True, help_text='Challenges or issues faced')),
                ('progress_percentage', models.PositiveSmallIntegerField(default=0, help_text='Progress percentage (0-100)')),
                ('is_public', models.BooleanField(default=True, help_text='Whether project is visible to public')),
                ('allow_comments', models.BooleanField(default=True, help_text='Allow public comments')),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'City Project',
                'verbose_name_plural': 'City Projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text="Font Awesome icon class (e.g., 'fas fa-road')", max_length=50)),
            ],
            options={
                'verbose_name': 'Project Category',
                'verbose_name_plural': 'Project Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('progress_percentage', models.PositiveSmallIntegerField(blank=True, help_text='Update progress if changed', null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/updates/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='projects.cityproject')),
            ],
            options={
                'verbose_name': 'Project Update',
                'verbose_name_plural': 'Project Updates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='projects/documents/%Y/%m/')),
                ('file_type', models.CharField(blank=True, help_text='e.g., PDF, Image, Plan', max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='projects.cityproject')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Project Document',
                'verbose_name_plural': 'Project Documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddField(
            model_name='cityproject',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='projects.projectcategory'),
        ),
        migrations.AddField(
            model_name='cityproject',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cityproject',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Department responsible for this project', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='reports.department'),
        ),
        migrations.AddField(
            model_name='cityproject',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='cityproject',
            index=models.Index(fields=['status', '-created_at'], name='projects_ci_status_eba9cf_idx'),
        ),
        migrations.AddIndex(
            model_name='cityproject',
            index=models.Index(fields=['category', '-created_at'], name='projects_ci_categor_e16057_idx'),
        ),
        migrations.AddIndex(
            model_name='cityproject',
            index=models.Index(fields=['is_public', '-created_at'], name='projects_ci_is_publ_32936c_idx'),
        ),
    ]
