# Generated by Django 5.2.4 on 2025-11-05 13:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_type', models.CharField(choices=[('road', 'Road/Pothole'), ('garbage', 'Garbage'), ('water', 'Water Leakage'), ('streetlight', 'Broken Streetlight'), ('sewage', 'Sewage/Drainage'), ('other', 'Other')], help_text='Category of the reported issue', max_length=20)),
                ('description', models.TextField(help_text='Detailed description of the issue')),
                ('location', models.CharField(help_text='Location of the issue (Ahmedabad only)', max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Latitude (optional, for map integration)', max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Longitude (optional, for map integration)', max_digits=9, null=True)),
                ('image', models.ImageField(blank=True, help_text='Optional photo of the issue', null=True, upload_to='report_images/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('resolved', 'Resolved')], default='pending', help_text='Current status of the report', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the report was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the report was last updated')),
                ('feedback', models.TextField(blank=True, help_text='Citizen feedback after issue is resolved', null=True)),
                ('rating', models.PositiveSmallIntegerField(blank=True, help_text='Citizen rating (1-5) after resolution', null=True)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Authority assigned to resolve the issue', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_reports', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='Citizen who submitted the report', on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
