# Generated by Django 5.2.4 on 2025-11-05 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_department_report_city_report_last_updated_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='other_issue',
            field=models.CharField(blank=True, help_text="If issue type is 'Other', specify here.", max_length=255, null=True),
        ),
    ]
