# Generated by Django 5.2.4 on 2025-11-05 12:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelExperience',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('description', models.TextField()),
                ('experience_type', models.CharField(choices=[('place', 'Place'), ('activity', 'Activity'), ('story', 'Travel Story'), ('tip', 'Travel Tip')], db_index=True, max_length=20)),
                ('category', models.CharField(blank=True, choices=[('nature', 'Nature'), ('adventure', 'Adventure'), ('food', 'Food & Drink'), ('culture', 'Culture'), ('history', 'History'), ('shopping', 'Shopping'), ('nightlife', 'Nightlife'), ('accommodation', 'Accommodation'), ('transport', 'Transport'), ('other', 'Other')], max_length=50)),
                ('location', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='travel_experiences/%Y/%m/%d/')),
                ('visited_on', models.DateField(blank=True, help_text='Date of visit or experience', null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='published', max_length=20)),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('upvotes_count', models.IntegerField(default=0)),
                ('comments_count', models.IntegerField(default=0)),
                ('views_count', models.IntegerField(default=0)),
                ('shares_count', models.IntegerField(default=0)),
                ('bookmarks_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_experiences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Travel Experience',
                'verbose_name_plural': 'Travel Experiences',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExperienceUpvote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience_upvotes', to=settings.AUTH_USER_MODEL)),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upvotes', to='FreeContribution.travelexperience')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExperienceReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(choices=[('spam', 'Spam'), ('inappropriate', 'Inappropriate Content'), ('misleading', 'Misleading Information'), ('duplicate', 'Duplicate'), ('offensive', 'Offensive'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_reviewed', models.BooleanField(default=False)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('action_taken', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience_reports', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_experience_reports', to=settings.AUTH_USER_MODEL)),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='FreeContribution.travelexperience')),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExperienceMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('document', 'Document')], default='image', max_length=20)),
                ('file', models.FileField(upload_to='experience_media/%Y/%m/%d/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='FreeContribution.travelexperience')),
            ],
            options={
                'verbose_name': 'Media File',
                'verbose_name_plural': 'Media Files',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExperienceComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment', models.TextField(max_length=1000)),
                ('is_approved', models.BooleanField(default=True)),
                ('likes_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='FreeContribution.experiencecomment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience_comments', to=settings.AUTH_USER_MODEL)),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='FreeContribution.travelexperience')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExperienceBookmark',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('note', models.TextField(blank=True, help_text='Personal note about this bookmark')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarked_experiences', to=settings.AUTH_USER_MODEL)),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='FreeContribution.travelexperience')),
            ],
            options={
                'verbose_name': 'Bookmark',
                'verbose_name_plural': 'Bookmarks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExperienceActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('view', 'View'), ('share', 'Share'), ('bookmark', 'Bookmark')], max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experience_activities', to=settings.AUTH_USER_MODEL)),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='FreeContribution.travelexperience')),
            ],
            options={
                'verbose_name': 'Activity',
                'verbose_name_plural': 'Activities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommentLike',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_likes', to=settings.AUTH_USER_MODEL)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='FreeContribution.experiencecomment')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('comment', 'user'), name='uq_comment_like')],
            },
        ),
        migrations.AddIndex(
            model_name='travelexperience',
            index=models.Index(fields=['experience_type', '-created_at'], name='FreeContrib_experie_1f1ca0_idx'),
        ),
        migrations.AddIndex(
            model_name='travelexperience',
            index=models.Index(fields=['status', '-created_at'], name='FreeContrib_status_7ba9b4_idx'),
        ),
        migrations.AddIndex(
            model_name='travelexperience',
            index=models.Index(fields=['user', '-created_at'], name='FreeContrib_user_id_dec885_idx'),
        ),
        migrations.AddConstraint(
            model_name='experienceupvote',
            constraint=models.UniqueConstraint(fields=('experience', 'user'), name='uq_experience_upvote'),
        ),
        migrations.AddConstraint(
            model_name='experiencereport',
            constraint=models.UniqueConstraint(fields=('experience', 'reported_by'), name='uq_experience_report'),
        ),
        migrations.AddIndex(
            model_name='experiencecomment',
            index=models.Index(fields=['experience', '-created_at'], name='FreeContrib_experie_a67f25_idx'),
        ),
        migrations.AddConstraint(
            model_name='experiencebookmark',
            constraint=models.UniqueConstraint(fields=('experience', 'user'), name='uq_experience_bookmark'),
        ),
        migrations.AddIndex(
            model_name='experienceactivity',
            index=models.Index(fields=['experience', 'activity_type'], name='FreeContrib_experie_5becbc_idx'),
        ),
    ]
