# Generated by Django 5.2.4 on 2025-11-05 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FreeContribution', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experiencemedia',
            options={},
        ),
        migrations.AlterField(
            model_name='experiencemedia',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
