# Generated by Django 5.2.4 on 2025-11-05 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FreeContribution', '0002_alter_experiencemedia_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experiencemedia',
            options={'ordering': ['order', '-created_at'], 'verbose_name': 'Media File', 'verbose_name_plural': 'Media Files'},
        ),
    ]
