# Generated by Django 4.2.25 on 2025-11-04 20:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the authority/department', max_length=200)),
                ('email', models.EmailField(help_text='Contact email for this authority', max_length=254)),
                ('phone', models.CharField(help_text='Contact phone number', max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('area', models.CharField(help_text='Area/ward covered by this authority', max_length=100)),
                ('department', models.CharField(help_text='Department name (e.g., Roads, Water, Sanitation)', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this authority is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Authority',
                'verbose_name_plural': 'Authorities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Reporter's full name", max_length=200)),
                ('email', models.EmailField(help_text="Reporter's email address", max_length=254)),
                ('phone', models.CharField(help_text="Reporter's phone number", max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'.", regex='^\\+?1?\\d{9,15}$')])),
                ('area', models.CharField(help_text='Area/ward name', max_length=100)),
                ('pincode', models.CharField(db_index=True, help_text='6-digit pincode', max_length=6, validators=[django.core.validators.RegexValidator(message='Pincode must be exactly 6 digits.', regex='^\\d{6}$')])),
                ('address', models.TextField(blank=True, help_text='Detailed address (optional)')),
                ('problem_type', models.CharField(choices=[('Roads', 'Roads & Infrastructure'), ('Water', 'Water Supply'), ('Sanitation', 'Sanitation & Waste'), ('Electricity', 'Electricity'), ('Other', 'Other')], default='Other', help_text='Type of problem', max_length=50)),
                ('description', models.TextField(help_text='Detailed description of the issue')),
                ('image', models.ImageField(blank=True, help_text='Photo of the issue (optional)', null=True, upload_to='reports/%Y/%m/%d/')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved'), ('Rejected', 'Rejected')], db_index=True, default='Pending', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of submitter', null=True)),
                ('user_agent', models.CharField(blank=True, help_text='User agent string', max_length=500)),
                ('authority', models.ForeignKey(blank=True, help_text='Assigned authority', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='UrbanSite.authority')),
            ],
            options={
                'verbose_name': 'User Report',
                'verbose_name_plural': 'User Reports',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text='Feedback message')),
                ('is_public', models.BooleanField(default=False, help_text='Whether this feedback should be visible to the reporter')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('authority', models.ForeignKey(help_text='Authority providing feedback', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks', to='UrbanSite.authority')),
                ('report', models.ForeignKey(help_text='Associated report', on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='UrbanSite.userreport')),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedbacks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='userreport',
            index=models.Index(fields=['pincode', '-timestamp'], name='UrbanSite_u_pincode_1eeea2_idx'),
        ),
        migrations.AddIndex(
            model_name='userreport',
            index=models.Index(fields=['status', '-timestamp'], name='UrbanSite_u_status_333e96_idx'),
        ),
    ]
